import SwiftUI
import AppKit

struct ContentView: View {
    @State private var jsonInput: String = ""
    @State private var dartClassName: String = "AutoGenerated"
    @State private var useJsonKey: Bool = true
    @State private var useCamelCase: Bool = true
    @State private var dartOutput: String = ""
    @State private var showCopiedAlert: Bool = false
    @State private var useJsonSerializable: Bool = true

    private let generator = DartGenerator()

    var body: some View {
        GeometryReader { geometry in
            ZStack {
                backgroundLayer
                VStack(spacing: 20) {
                    headerSection
                    HStack(alignment: .top, spacing: 16) {
                        panel(
                            title: "JSON 输入",
                            caption: "粘贴原始数据并自动转换",
                            systemImage: "square.and.pencil"
                        ) {
                            GlassField {
                                JsonTextEditor(text: $jsonInput, onTextChange: generateDart)
                                    .font(.system(.body, design: .monospaced))
                                    .frame(minHeight: 220, maxHeight: .infinity)
                            }
                            .frame(maxHeight: .infinity)
                            .overlay(alignment: .topLeading) {
                                if jsonInput.isEmpty {
                                    Text("粘贴你的 JSON 到这里...")
                                        .foregroundColor(Color.white.opacity(0.55))
                                        .padding(.horizontal, 24)
                                        .padding(.vertical, 20)
                                        .allowsHitTesting(false)
                                }
                            }
                        }

                        panel(
                            title: "Dart 类",
                            caption: "复制生成的模型代码",
                            systemImage: "chevron.left.slash.chevron.right"
                        ) {
                            GlassField {
                                OutputTextView(text: dartOutput)
                                    .frame(minHeight: 220, maxHeight: .infinity)
                            }
                            .frame(maxHeight: .infinity)
                            .overlay(alignment: .topLeading) {
                                if dartOutput.isEmpty {
                                    Text("Dart 代码将在这里显示...")
                                        .foregroundColor(Color.white.opacity(0.55))
                                        .padding(.horizontal, 24)
                                        .padding(.vertical, 20)
                                        .allowsHitTesting(false)
                                }
                            }
                        }
                    }
                    .frame(minHeight: 220, maxHeight: min(geometry.size.height * 0.55, 320))

                    optionsPanel
                        .layoutPriority(1)
                }
                .padding(.horizontal, 30)
                .padding(.vertical, 24)
                .frame(width: geometry.size.width, height: geometry.size.height, alignment: .top)
            }
        }
        .onAppear {
            generateDart()
        }
    }

    private var backgroundLayer: some View {
        ZStack {
            LinearGradient(
                colors: [
                    Color(red: 18/255, green: 24/255, blue: 34/255),
                    Color(red: 10/255, green: 12/255, blue: 24/255),
                    Color(red: 6/255, green: 8/255, blue: 18/255)
                ],
                startPoint: .topLeading,
                endPoint: .bottomTrailing
            )

            Circle()
                .fill(Color.accentColor.opacity(0.25))
                .frame(width: 420)
                .blur(radius: 160)
                .offset(x: -240, y: -220)

            Circle()
                .fill(Color.purple.opacity(0.18))
                .frame(width: 460)
                .blur(radius: 180)
                .offset(x: 280, y: 200)
        }
        .ignoresSafeArea()
    }

    private var headerSection: some View {
        HStack(alignment: .center, spacing: 18) {
            ZStack {
                RoundedRectangle(cornerRadius: 18, style: .continuous)
                    .fill(
                        LinearGradient(
                            colors: [
                                Color.accentColor.opacity(0.92),
                                Color.accentColor.opacity(0.65)
                            ],
                            startPoint: .topLeading,
                            endPoint: .bottomTrailing
                        )
                    )

                Image(systemName: "curlybraces")
                    .font(.system(size: 26, weight: .bold))
                    .foregroundColor(.white)
            }
            .frame(width: 58, height: 58)

            VStack(alignment: .leading, spacing: 4) {
                Text("JSON to Dart")
                    .font(.system(size: 22, weight: .semibold))
                    .foregroundColor(Color.white.opacity(0.95))

                Text("将 JSON 快速转换为可维护的 Dart 模型")
                    .font(.system(size: 13, weight: .medium))
                    .foregroundColor(Color.white.opacity(0.65))
            }

            Spacer()
        }
        .padding(.vertical, 16)
        .padding(.horizontal, 22)
        .glassCard(cornerRadius: 18)
    }

    @ViewBuilder
    private func panel<Content: View>(title: String, caption: String, systemImage: String, @ViewBuilder content: () -> Content) -> some View {
        VStack(alignment: .leading, spacing: 16) {
            HStack(alignment: .center, spacing: 14) {
                Image(systemName: systemImage)
                    .font(.system(size: 18, weight: .semibold))
                    .foregroundColor(Color.white.opacity(0.9))
                    .frame(width: 38, height: 38)
                    .background(
                        Circle()
                            .fill(Color.white.opacity(0.08))
                            .overlay(
                                Circle()
                                    .stroke(Color.white.opacity(0.18), lineWidth: 1)
                            )
                    )

                VStack(alignment: .leading, spacing: 2) {
                    Text(title)
                        .font(.system(size: 17, weight: .semibold))
                        .foregroundColor(Color.white.opacity(0.92))

                    Text(caption)
                        .font(.system(size: 12, weight: .medium))
                        .foregroundColor(Color.white.opacity(0.6))
                }
            }

            content()
        }
        .padding(20)
        .glassCard(cornerRadius: 18)
        .frame(maxWidth: .infinity, maxHeight: .infinity)
    }

    private var optionsPanel: some View {
        VStack(alignment: .leading, spacing: 16) {
            HStack(alignment: .center, spacing: 16) {
                VStack(alignment: .leading, spacing: 4) {
                    Text("生成配置")
                        .font(.system(size: 16, weight: .semibold))
                        .foregroundColor(Color.white.opacity(0.92))

                    Text("调节生成方式并导出结果")
                        .font(.footnote)
                        .foregroundColor(Color.white.opacity(0.65))
                }

                Spacer(minLength: 24)

                VStack(alignment: .leading, spacing: 4) {
                    Text("类名")
                        .font(.system(size: 13, weight: .medium))
                        .foregroundColor(Color.white.opacity(0.65))

                    TextField("类名", text: $dartClassName)
                        .textFieldStyle(.plain)
                        .font(.system(size: 14, weight: .semibold))
                        .foregroundColor(Color.white.opacity(0.92))
                        .padding(.vertical, 6)
                        .padding(.horizontal, 10)
                        .background(
                            RoundedRectangle(cornerRadius: 14, style: .continuous)
                                .fill(Color.white.opacity(0.08))
                                .overlay(
                                    RoundedRectangle(cornerRadius: 14, style: .continuous)
                                        .stroke(Color.white.opacity(0.16), lineWidth: 1)
                                )
                        )
                        .frame(width: 220)
                        .onChange(of: dartClassName) { _ in
                            generateDart()
                        }
                }

                if showCopiedAlert {
                    Label("已复制到剪贴板", systemImage: "checkmark.circle.fill")
                        .font(.system(size: 13, weight: .semibold))
                        .foregroundColor(Color.green.opacity(0.9))
                        .padding(.leading, 8)
                        .transition(.move(edge: .trailing).combined(with: .opacity))
                }
            }

            HStack(spacing: 14) {
                Toggle("使用 json_serializable", isOn: $useJsonSerializable)
                    .toggleStyle(.switch)
                    .controlSize(.small)
                    .tint(Color.accentColor)
                    .onChange(of: useJsonSerializable) { _ in
                        generateDart()
                    }

                Toggle("JsonKey 注解", isOn: $useJsonKey)
                    .toggleStyle(.switch)
                    .controlSize(.small)
                    .tint(Color.accentColor)
                    .disabled(!useJsonSerializable)
                    .onChange(of: useJsonKey) { _ in
                        generateDart()
                    }

                Toggle("使用 camelCase", isOn: $useCamelCase)
                    .toggleStyle(.switch)
                    .controlSize(.small)
                    .tint(Color.accentColor)
                    .onChange(of: useCamelCase) { _ in
                        generateDart()
                    }

                Spacer(minLength: 0)
            }
            .frame(maxWidth: .infinity, alignment: .leading)

            Divider()
                .overlay(Color.white.opacity(0.12))

            HStack(spacing: 12) {
                Button(action: formatJson) {
                    Label("格式化 JSON", systemImage: "sparkles")
                }
                .buttonStyle(ActionButtonStyle(variant: .tinted))

                Button(action: copyToClipboard) {
                    Label("复制代码", systemImage: "doc.on.doc")
                }
                .buttonStyle(ActionButtonStyle(variant: .primary))

                Button(action: downloadFile) {
                    Label("下载文件", systemImage: "arrow.down.doc")
                }
                .buttonStyle(ActionButtonStyle(variant: .secondary))

                Spacer()
            }
        }
        .padding(18)
        .glassCard(cornerRadius: 18)
    }

    private func generateDart() {
        guard !jsonInput.isEmpty else {
            dartOutput = ""
            return
        }

        let options = DartGeneratorOptions(
            className: dartClassName.isEmpty ? "AutoGenerated" : dartClassName,
            useJsonKey: useJsonKey && useJsonSerializable,
            useCamelCase: useCamelCase,
            useJsonSerializable: useJsonSerializable
        )

        dartOutput = generator.generate(from: jsonInput, options: options)
    }

    private func formatJson() {
        guard let jsonData = jsonInput.data(using: .utf8),
              let jsonObject = try? JSONSerialization.jsonObject(with: jsonData),
              let formattedData = try? JSONSerialization.data(withJSONObject: jsonObject, options: [.prettyPrinted, .sortedKeys]),
              let formattedString = String(data: formattedData, encoding: .utf8) else {
            return
        }

        jsonInput = formattedString
    }

    private func copyToClipboard() {
        let pasteboard = NSPasteboard.general
        pasteboard.clearContents()
        pasteboard.setString(dartOutput, forType: .string)

        withAnimation(.spring(response: 0.4, dampingFraction: 0.75)) {
            showCopiedAlert = true
        }

        DispatchQueue.main.asyncAfter(deadline: .now() + 2) {
            withAnimation(.easeOut(duration: 0.3)) {
                showCopiedAlert = false
            }
        }
    }

    private func downloadFile() {
        let panel = NSSavePanel()
        panel.allowedContentTypes = [.init(filenameExtension: "dart")!]
        panel.nameFieldStringValue = "\(dartClassName.isEmpty ? "AutoGenerated" : dartClassName).dart"

        panel.begin { response in
            if response == .OK, let url = panel.url {
                try? dartOutput.write(to: url, atomically: true, encoding: .utf8)
            }
        }
    }
}

private struct ActionButtonStyle: ButtonStyle {
    enum Variant {
        case primary
        case secondary
        case tinted
    }

    var variant: Variant = .primary

    func makeBody(configuration: Configuration) -> some View {
        configuration.label
            .font(.system(size: 14, weight: .semibold))
            .padding(.vertical, 10)
            .padding(.horizontal, 18)
            .background(
                LinearGradient(
                    colors: variant.gradientColors,
                    startPoint: .topLeading,
                    endPoint: .bottomTrailing
                )
                .opacity(configuration.isPressed ? 0.85 : 1)
            )
            .foregroundStyle(variant.foregroundColor)
            .clipShape(Capsule())
            .shadow(color: variant.shadowColor.opacity(configuration.isPressed ? 0.22 : 0.4), radius: 12, y: 6)
            .scaleEffect(configuration.isPressed ? 0.97 : 1)
            .animation(.spring(response: 0.3, dampingFraction: 0.7), value: configuration.isPressed)
    }
}

private extension ActionButtonStyle.Variant {
    var gradientColors: [Color] {
        switch self {
        case .primary:
            return [
                Color.accentColor,
                Color.accentColor.opacity(0.75)
            ]

        case .secondary:
            return [
                Color.white.opacity(0.22),
                Color.white.opacity(0.08)
            ]

        case .tinted:
            return [
                Color(red: 0.55, green: 0.44, blue: 1),
                Color(red: 0.35, green: 0.64, blue: 1)
            ]
        }
    }

    var foregroundColor: Color {
        switch self {
        case .primary, .tinted:
            return .white

        case .secondary:
            return Color.white.opacity(0.92)
        }
    }

    var shadowColor: Color {
        switch self {
        case .primary:
            return Color.accentColor.opacity(0.45)

        case .secondary:
            return Color.black.opacity(0.25)

        case .tinted:
            return Color(red: 0.35, green: 0.64, blue: 1).opacity(0.35)
        }
    }
}

private struct GlassCardModifier: ViewModifier {
    var cornerRadius: CGFloat

    func body(content: Content) -> some View {
        content
            .background(
                RoundedRectangle(cornerRadius: cornerRadius, style: .continuous)
                    .fill(.ultraThinMaterial)
                    .overlay(
                        RoundedRectangle(cornerRadius: cornerRadius, style: .continuous)
                            .stroke(Color.white.opacity(0.12), lineWidth: 0.8)
                    )
            )
            .clipShape(RoundedRectangle(cornerRadius: cornerRadius, style: .continuous))
            .shadow(color: Color.black.opacity(0.18), radius: 18, y: 12)
    }
}

private extension View {
    func glassCard(cornerRadius: CGFloat = 16) -> some View {
        modifier(GlassCardModifier(cornerRadius: cornerRadius))
    }
}

private struct GlassField<Content: View>: View {
    var cornerRadius: CGFloat
    var contentPadding: CGFloat
    let content: Content

    init(cornerRadius: CGFloat = 14, contentPadding: CGFloat = 16, @ViewBuilder content: () -> Content) {
        self.cornerRadius = cornerRadius
        self.contentPadding = contentPadding
        self.content = content()
    }

    var body: some View {
        content
            .padding(contentPadding)
            .background(
                RoundedRectangle(cornerRadius: cornerRadius, style: .continuous)
                    .fill(.ultraThinMaterial)
                    .overlay(
                        RoundedRectangle(cornerRadius: cornerRadius, style: .continuous)
                            .stroke(Color.white.opacity(0.08), lineWidth: 0.8)
                    )
            )
            .clipShape(RoundedRectangle(cornerRadius: cornerRadius, style: .continuous))
            .shadow(color: Color.black.opacity(0.12), radius: 12, y: 8)
    }
}

struct JsonTextEditor: NSViewRepresentable {
    @Binding var text: String
    var onTextChange: () -> Void

    func makeNSView(context: Context) -> NSScrollView {
        let scrollView = NSTextView.scrollableTextView()
        scrollView.backgroundColor = .clear
        scrollView.drawsBackground = false

        let textView = scrollView.documentView as! NSTextView
        textView.delegate = context.coordinator
        textView.isAutomaticQuoteSubstitutionEnabled = false
        textView.isAutomaticDashSubstitutionEnabled = false
        textView.isAutomaticTextReplacementEnabled = false
        textView.isAutomaticSpellingCorrectionEnabled = false
        textView.font = NSFont.monospacedSystemFont(ofSize: NSFont.systemFontSize + 1, weight: .regular)
        textView.string = text
        textView.isRichText = false
        textView.textColor = NSColor(calibratedWhite: 0.95, alpha: 1)
        textView.insertionPointColor = NSColor.systemTeal
        textView.drawsBackground = false
        textView.textContainerInset = NSSize(width: 0, height: 0)
        textView.textContainer?.lineFragmentPadding = 0

        context.coordinator.textView = textView

        return scrollView
    }

    func updateNSView(_ nsView: NSScrollView, context: Context) {
        let textView = nsView.documentView as! NSTextView
        if textView.string != text && !context.coordinator.isInternalUpdate {
            textView.string = text
        }
    }

    func makeCoordinator() -> Coordinator {
        Coordinator(self)
    }

    class Coordinator: NSObject, NSTextViewDelegate {
        var parent: JsonTextEditor
        var textView: NSTextView?
        var isInternalUpdate = false

        init(_ parent: JsonTextEditor) {
            self.parent = parent
        }

        func textDidChange(_ notification: Notification) {
            guard let textView = notification.object as? NSTextView else { return }

            isInternalUpdate = true

            DispatchQueue.main.async { [weak self] in
                guard let self = self else { return }
                self.parent.text = textView.string
                self.parent.onTextChange()
                self.isInternalUpdate = false
            }
        }
    }
}

private struct OutputTextView: NSViewRepresentable {
    var text: String

    func makeNSView(context: Context) -> NSScrollView {
        let scrollView = NSTextView.scrollableTextView()
        scrollView.backgroundColor = .clear
        scrollView.drawsBackground = false

        let textView = scrollView.documentView as! NSTextView
        textView.isEditable = false
        textView.isSelectable = true
        textView.string = text
        textView.font = NSFont.monospacedSystemFont(ofSize: NSFont.systemFontSize + 1, weight: .regular)
        textView.textColor = NSColor(calibratedWhite: 0.95, alpha: 1)
        textView.drawsBackground = false
        textView.textContainerInset = NSSize(width: 0, height: 0)
        textView.textContainer?.lineFragmentPadding = 0

        return scrollView
    }

    func updateNSView(_ nsView: NSScrollView, context: Context) {
        let textView = nsView.documentView as! NSTextView
        textView.string = text
    }
}

#Preview {
    ContentView()
}
